linters:
  enable:
    - gocyclo
    - dupl
    - lll
    - gocritic
    - gofmt
    - gosec
    - errorlint
    - goconst
    - revive
linters-settings:
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 50
  gosec:
    excludes:
      - G404